### ISSUE TITLE
Request for DCGAN with MAML code

### ISSUE THREAD

**Issue by BassantTolba1234** [usc599resl/mlgm#4]
Dear Sir,
Brilliant work !..
Can you kindly share with me the code of DCGAN with MAML , I will be very grateful for you.
I'm waiting for your reply..
Best Regards,

**Comment by utkarshjp7** [comment]
It is under `maml_gan` branch.

**Comment by BassantTolba1234** [comment]
Dear Sir, 
Thank you very much for your reply and brilliant efforts..
Can you kindly share the link of MAML_GAN branch with me..
I will be very grateful for you.
Thanks in advance.
Best Regards,
